import React from 'react'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { getServerSession } from 'next-auth'

import SessionProvider from '../components/SessionProvider'

import './globals.css'
import NavBar from '@/components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const session = await getServerSession()

    return (
        <html lang="en">
            <body className={inter.className}>
                <SessionProvider session={session}>
                    <main className="flex min-h-screen flex-col">
                        <NavBar />
                        {children}
                    </main>
                </SessionProvider>
            </body>
        </html>
    )
}
